### ISSUE TITLE
broken link on Contribute page

### ISSUE THREAD

**Issue by doniks** [ubports/docs.ubports.com#10]
https://docs.ubports.com/en/latest/contribute/index.html

It says "If you’re just getting started, we always need help with :ref:`thorough bug reporting <contribute-bugreporting-index>`_. If you are multilingual, translations are also a great place to start."

I'm not sure how to fix this myself. It seems that removing the underscore helps. However, I have to `python -m sphinx . _build` at least TWICE for any change in this file to take effect, so maybe something else is going wrong here.

**Comment by UniversalSuperBox** [comment]
I wasn't able to reproduce the issue of needing to build twice to fix the issue. ¯\_(ツ)_/¯
