### ISSUE TITLE
Desktop applications section instructions is incomete, skips the installation instructions

### ISSUE THREAD

**Issue by YougoCodes** [ubports/docs.ubports.com#117]
I think the instructions on https://docs.ubports.com/en/latest/userguide/dailyuse/libertine.html are incomplete. It assumes libertine is already present and just tells you to install the scope. You need to follow instructions on https://wiki.ubuntu.com/Touch/Libertine first

I'm willing to make a pull request to 
- add the instructions from  https://wiki.ubuntu.com/Touch/Libertine 
Or
- add a link to https://wiki.ubuntu.com/Touch/Libertine

**Comment by YougoCodes** [comment]
Follow-up as i discussed matters:

- Libertinere and xmir are installed by default on 15.04 and operable via cli, so does not need extra instructions
- Libertine-scope is in the open store, so does not need to be pulled from external repo
- The libertine gui app is not in the open store, but is installed at some point following the instructions on the ubuntu wiki. It is working well for me.

Isolating the gui app from the repository and getting it into the open store (preferrably with a maintainer) would make things comlete, also considering making it available in 16.04.

So:
Add instructions on how to get the gui app?
Add a link to the ubuntu wiki for reference?

**Comment by doniks** [comment]
> Add instructions on how to get the gui app?
> Add a link to the ubuntu wiki for reference?

Can't hurt to document it! Would give the gui app more exposure and might motivate a maintainer. Let's make it clear that it's optional/extra/unmaintained

**Comment by UniversalSuperBox** [comment]
Libertine is now included in Ubuntu Touch, there is no need to install it.
