### ISSUE TITLE
App development, system software: missing information 

### ISSUE THREAD

**Issue by padraic7a** [ubports/docs.ubports.com#134]
http://docs.ubports.com/en/latest/appdev/system-software.html

If I follow the steps for "Building on the device itself" and enter
```sudo apt-get build-dep address-book-app```
I am told that
```you must put some 'source' URIs in your sources.list```

What are the correct sources to list?

**Comment by padraic7a** [comment]
After thinking about it a bit I checked that /etc/apt/source.list **does** actually contain sources. ```sudo apt update``` resolved the problem. 

I'm not sure if that's worth putting in the documentation or not. I'll leave the issue open for discussion- if it is worth adding I'm happy to write it up. If it's a non-issue that's also fine obviously.

**Comment by doniks** [comment]
Pull requests to improve the docs are always welcome! Sounds like adding that one command line would do?! what do you think? Let's stick to ONE style though. Either all ``apt-get`` or all ``apt``.

**Comment by padraic7a** [comment]
Very good, I will get on it in the next couple of days.

**Comment by dobey** [comment]
It would probably be even better if the docs documented how to create a chroot from the rootfs tarball, in the home directory (or on an SD card), and then instructed to build inside the chroot, to avoid having to deal with remounting / and likely filling up the root partition.

**Comment by padraic7a** [comment]
That's a good idea. I didn't have enough disk space to follow the instructions all the way.
If you give me a couple of pointers on how to create that chroot I can write up and test a new section.

**Comment by dobey** [comment]
@padraic7a https://askubuntu.com/a/623311/50737

Replace the URL and rootfs tarball name there, with the ones from the https://cdimage.ubports.com/ site, for the version you're interested in building against, I think, and should be good to go.

**Comment by padraic7a** [comment]
Ok, give me a few days and I'll get on it.

**Comment by doniks** [comment]
I think this is outdated. Feel free to reopen if there is still something amiss/ you are still intending to improve something
