### ISSUE TITLE
The section about App development - On device needs an overhaul

### ISSUE THREAD

**Issue by doniks** [ubports/docs.ubports.com#17]
I find this section really hard to read
https://docs.ubports.com/en/latest/appdev/index.html#on-device-software-development

It reads like blog posts copied over. The text doesn't integrate into the website. It is an entanglement of some generic UT app dev aspects with two very specific IDEs without clear structure what goes where. Some places are walls of text. Some places look like malformed markups.

**Comment by NeoTheThird** [comment]
See #34.

**Comment by UniversalSuperBox** [comment]
Merged, resolving the issue. Thanks!
