### ISSUE TITLE
UserMetrics tutorial missed important points

### ISSUE THREAD

**Issue by kugiigi** [ubports/docs.ubports.com#172]
## Description
For the user metrics to work, there are 2 important points that should be mentioned in the document.

1. "usermetrics" policy must be added to the apparmor configuration file.
2. The property "name" MUST be provided as this is like the ID for storing the user metric data.

**Comment by userj** [comment]
Good points. They will be added in the next update. Thanks!

**Comment by doniks** [comment]
If I understand it correctly, this is fixed.
