### ISSUE TITLE
how much disk space needed to build Ubuntu Touch?

### ISSUE THREAD

**Issue by bam80** [ubports/docs.ubports.com#197]
We didn't find if it's mentioned in the docs.

@sashakrava

**Comment by lduboeuf** [comment]
hello, better to move that question in forum or chat or add an issue in a more general place. 
I guess it would require a lot in a single computer

**Comment by doniks** [comment]
Closing this, since it seems un-actionable. Building ALL OF UT? Probably nobody knows. Probably nobody every built everything on a single machine at the same time.
