### ISSUE TITLE
Update libertine documentation

### ISSUE THREAD

**Issue by Ingo-FP-Angel** [ubports/docs.ubports.com#210]
The existing libertine documentation at http://docs.ubports.com/en/latest/userguide/dailyuse/libertine.html is not up-to-date, e.g. the app-scope doesn't have to be installed from the openstore anymore and containers can be created/managed from the settings in addition to the CLI.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/docs.ubports.com/pull/223
