### ISSUE TITLE
Desktop apps not supported on my nexus 5

### ISSUE THREAD

**Issue by baruchiro** [ubports/docs.ubports.com#217]
In https://github.com/ubports/docs.ubports.com/blob/master/userguide/dailyuse/libertine.rst you say to download the [Desktop Apps](https://open-store.io/app/libertine-scope.ubuntu) app, but the OpenStore says it is not supported on my Nexus 5 Ubuntu Touch 16.

**Comment by UniversalSuperBox** [comment]
Hello @baruchiro,

Sorry I didn't see this sooner, the text was fixed by https://github.com/ubports/docs.ubports.com/pull/223. There is no longer a need to download the desktop apps scope, it is included with Ubuntu Touch.
