### ISSUE TITLE
Documentation partially translated in French even if Weblate is at 100% complete

### ISSUE THREAD

**Issue by Anne017** [ubports/docs.ubports.com#241]
The French translation is complete at 100% on [Weblate](https://translate.ubports.com/languages/fr/ubports-docs/) since a couple of months, but the [Documentation](http://docs.ubports.com/fr/latest/contribute/translations.html) is still partially translated.

Could you please refresh the Documentation with the latest version of the translations?

Thanks in advance.

**Comment by UniversalSuperBox** [comment]
Yes, thank you. https://github.com/ubports/docs.ubports.com/pull/251 fixes this.

**Comment by UniversalSuperBox** [comment]
Should be fixed by #251
