### ISSUE TITLE
docs.ubports.com has a new Mascot

### ISSUE THREAD

**Issue by Acid-Override** [ubports/docs.ubports.com#26]
![unicorn-gold-hed-2016](https://user-images.githubusercontent.com/33676024/32977346-b071de6e-cbf9-11e7-9073-1984f51d2999.jpg)

Ok... so not exactly what you had in mind?  But (no pun intended) now that you are here I'd like to take this opportunity to let you know that UBports is recruiting writers to help with the documentation.  If you like to write and are interested in helping UBports grow and prosper, then let us know!

Thanks!
UBdocs Teams

**Comment by NeoTheThird** [comment]
![rly?](https://media.giphy.com/media/26gYK80dicRdI8bYI/giphy.gif)
