### ISSUE TITLE
Docs: Release Schedule: Missing description regarding edge

### ISSUE THREAD

**Issue by ppsilva** [ubports/docs.ubports.com#260]
I couldn't find info regarding the edge channel which is possible to install via the GUI installer.

[docs.ubports.com/about/process/release-schedule.rst](https://github.com/ubports/docs.ubports.com/blob/master/about/process/release-schedule.rst)

**Comment by doniks** [comment]
I'm not sure we really need to document edge. By it's very nature it is bleeding edge development, forges new paths, changes what it is, changes the rules under which it operates, including, but very definitely not limited to it's build/release schedule. For situations like this, it truely, truely holds that the code is the documentation
