### ISSUE TITLE
After install clickable section incorrect

### ISSUE THREAD

**Issue by Abuabdelah** [ubports/docs.ubports.com#313]
after installing `clickable` the command mentioned below and in this [link](https://clickable-ut.dev/en/latest/install.html#after-install) doesn't work!

> Let Clickable setup docker (it could ask for the sudo password): clickable setup

```
clickable setup
There is no builtin or custom command named "setup"
```

**Comment by doniks** [comment]
Interesting. Clickable is managed over here though: https://gitlab.com/clickable/clickable/blob/master/docs/install.rst So, better to raise it there. 
Or, better yet, do you know what it should be instead? Have you just installed it and got started with it and figured out what to run instead? Then maybe you can propose a merge request with a fix ...
