### ISSUE TITLE
Another amend to Shell access via ssh page

### ISSUE THREAD

**Issue by clendee** [ubports/docs.ubports.com#315]
Where it says:

Now start the ssh server:

`sudo android-gadget-service enable ssh`

This didnt start the ssh server on the phone for me, I had to add

`sudo service ssh start`

as I was getting many connection refused errors on trying to connect from my machine.

These may be simple things but for beginners who are copying line by line I think it needs to be clear.

**Comment by thebencourt** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/690479/97114186-e712f300-16e6-11eb-9634-bac2f0329e3d.png">

Looks like this bug can be closed as the extra command is now on the page
