### ISSUE TITLE
Request - Adding more adb commands to the 'Shell access via adb' page

### ISSUE THREAD

**Issue by clendee** [ubports/docs.ubports.com#316]
For example

    adb push [source] [destination] – Pushes a file from your computer to your Ubuntu Touch device.
    adb pull [destination] [source] – Pulls a file from your UT device to your computer – works like adb push, but in reverse.

    adb shell – Gives you access to the Linux command-line shell on your device.
    adb shell command – Runs the specified shell command on your device.

**Comment by gfda** [comment]
### Get and Set Properties

```shell
adb shell getprop - Lists all system properties and their values.
adb shell setprop [property] [value] - Sets the value to a specific property.
```

### Networking
```shell
adb shell netstat -t - Lists TCP information.
adb shell ping <ip addr> - Ping to IP address.
```

### Process
```shell
adb shell ps -A - Lists all processes.  
adb shell top - Show all current process/activity in real-time.
```

**Comment by thebencourt** [comment]
Happy to create a PR adding these to the page, are they all wanted or if not which ones?

**Comment by doniks** [comment]
great. I think push, pull, shell would be nice.

I'm less convinced about netcat, ping, ps and top. Those don't really have specific relation to adb, let alone UT, they're just regular linux terminal commands. Just like ls, find, less, etc. If someone cares about them, then the know it already. If they don't know about them, I don't think the adb documentation of UT is the best place to educate about them. 

With getprop, setprop, ok, yes they are specific to the Android ports of UT, so relate to adb, but still, why do we need to document them in UT? There is also port forwarding and probably a bunch of other stuff that one can theoretically do with adb in UT https://developer.android.com/studio/command-line/adb . But I would only document if there is a meaningful use case to do this with UT.

What do you think?

**Comment by thebencourt** [comment]
Sounds good to me, I'll get those added later
