### ISSUE TITLE
Update github About section to include UBDocs telegram group details

### ISSUE THREAD

**Issue by sanathusk** [ubports/docs.ubports.com#341]
Please add a link to the telegram UBDocs group so that it is easier for new users to reach the UBDocs team. Please find in attachment a screenshot of another repo for better understanding.
![Screenshot 2020-09-27 at 9 10 45 PM](https://user-images.githubusercontent.com/19380158/94369266-5c9a9c00-0106-11eb-96b9-0ebebff773b9.png)

**Comment by doniks** [comment]
The group is intentionally private. There are plenty places where things can be discussed in public. The docs telegram group is private and invitation only, so it is possible to focus on one thing only: contributions to the docs. if you want to contribute you can make a PR or start a conversation in one of the many public places.

**Comment by sanathusk** [comment]
Thanks
