### ISSUE TITLE
Wi-fi broken after trying to follow the Android apps guide on Hammerhead

### ISSUE THREAD

**Issue by lukepozen** [ubports/docs.ubports.com#379]
- Device: Hammerhead
- Channel: stable
- Build: OTA-15

### Steps to reproduce
 I followed the Android apps wiki guide after a fresh install of stable channel (OTA.15), Hammerhead (https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html).

Specifically, after:

```
wget http://cdimage.ubports.com/anbox-images/anbox-boot-$CODENAME.img
adb shell # connect from your host computer to your UT device
sudo reboot -f bootloader # 'adb shell' will exit after this command, the prompt will be back on your host
sudo fastboot flash $PARTITIONNAME anbox-boot-$CODENAME.img
sudo fastboot reboot
rm anbox-boot-$CODENAME.img
exit
```
when the phone rebooted, and I used the following commands:
```

adb shell # connect from your host computer to your UT device
sudo mount -o rw,remount /
sudo apt update
```

... I wasn't any more able to update the software. Looking at the Configuration panel there is no more evidence of **any** wifi connection (even the one I normally used before) ...

**Comment by lukepozen** [comment]
Thanks a lot, Dalton!

**Comment by UniversalSuperBox** [comment]
These steps were removed from the Anbox documentation for OTA-16 in https://github.com/ubports/docs.ubports.com/pull/400
