### ISSUE TITLE
Broken link to Krillin ROM

### ISSUE THREAD

**Issue by Bolly** [ubports/docs.ubports.com#384]
The link to Krillin's ROM is broken, it's the only one that's broken.
https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices

**Comment by lduboeuf** [comment]
oh yes true, @Flohack74 any idea ?

**Comment by doniks** [comment]
indeed. seems there are even more broken links on that page https://github.com/ubports/docs.ubports.com/issues/388 

I'm closing this issue in favor of the other 'larger' one

**Comment by Fuseteam** [comment]
looks like krillin is in the archive: http://web.archive.org/web/20200820100356if_/https://cdimage.ubports.com/ubports-installer/krillin/e45.zip
