### ISSUE TITLE
multiple broken links on docs.ubports (bq/meizu)

### ISSUE THREAD

**Issue by Matte26** [ubports/docs.ubports.com#388]
There are currently 4 out of 5 links to the legacy devices rom that are not working, redirecting users to an error page.
In particular, Bq E4.5 (krillin), Bq E5 HD (vegetahd), Bq M10 HD (cooler), Bq M10 FHD (frieza) are not working.
Meizu MX4 (arale) is the only currently working link.

**Comment by lduboeuf** [comment]
here ? : https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices

**Comment by Matte26** [comment]
Yeah, those are the links I was referring to, forgot to link the page, my bad

**Comment by doniks** [comment]
> This is more or less uncharted territory.

it seems it became a bit more uncharted :( those were strange links to begin with ... some binary file on someones google file share ... 

fwiw, [ubuntuusers.de](https://wiki.ubuntuusers.de/Ubuntu_Touch/flash_tool/#Android-auf-ein-BQ-Geraet-flashen) is now linking to [some other forum](https://www.android-hilfe.de/forum/bq-allgemein.2373/software-repository-fuer-treiber-tools-firmware.964197.html) where there supposedly is a link to a telegram channels where some binary files are being shared ...

**Comment by Matte26** [comment]
Checked it out, if I'm not mistaken, that telegram group only hosts the android roms, not the UT ones needed to make the first conversion of legacy devices before updating them with ut installer

**Comment by Matte26** [comment]
As per ubuntuusers.de, the links they provide to those legacy devices ut fw, are the very same as the ones os docs.ubports, therefore broken as well

**Comment by Fuseteam** [comment]
seems vegetahd is available in web archive: http://web.archive.org/web/20200820100403if_/https://storage.googleapis.com/otas/2014/Smartphones/Aquaris_E5_HD/Ubuntu/VEGETA01A-S11A_BQ_L100EN_2017_170207.zip
credits to @amyosx for finding it

**Comment by TartanSpartan** [comment]
This is the cooler legacy image. The upload will only persist for a week, but hopefully that should suffice.

https://we.tl/t-uGsdbSqtFj

**Comment by doniks** [comment]
Thanks guys! Images have been placed here: https://cdimage.ubports.com/stock-bq-images/

Does one of you want to make a PR to fix the docs? I could do it, but I usually struggle to find someone to review my PR's, so it will be fastest if someone else proposes and I review.

**Comment by TartanSpartan** [comment]
Yeah, I can do that fairly soon :) I've been practicing Git-fu over the past couple of weeks.

**Comment by Bolly** [comment]
Sorry @TartanSpartan, but it seemed a bit urgent. 😊
