### ISSUE TITLE
Move documents from old wiki

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/docs.ubports.com#4]
Some documents from [the old wiki](https://wiki.ubports.com/wiki/Home) are very relevant and we should continue to use them (after reformatting them in ReStructuredText, of course). 

The ones I see at first glance are:

- [x] Install UBports
- [x] Use ADB from Desktop
- [ ] *DAV synchronization
- [x] Install 16.04
- [x] Set up app development environment
- [x] Set up app development environment in container
- [x] Set up Cordova app development environment in container
- [x] Writing a good bug report
- [x] UBports Bug Trackers
- [x] Release Channels
- [ ] How a UBports image is built
- [ ] Building libhybris
- [x] Porting Information (And subpages)

**Comment by doniks** [comment]
## Add ##
I would vote to also include  
 * Web Browser app debugging 
 * Getting started with translations
 * How to flash existing ubuntu touch devices with Ubports images (merge into the install page)

## Consider ##
Other pages, where I have a less strong opinion, but they carry some content
 * Image channels 
 * Release Channels 
 * BQ m10 FHD workarounds 
 * How to work around missing ADB functionality (I really can't speak to the quality/correctness :( )

## Porting ##
I would propose a simple link collection pointing to halium *and* to the old wiki. No point making the old wiki stuff shine. However, also halium doesn't seem to have taken over everything just yet (e.g., no ubports rootfs visible on the halium side anywhere). 
 * UBPorts Porting Information
 * Device Development Information
 * Building libhybris
 * How a UBports Image is Built

**Comment by UniversalSuperBox** [comment]
I've updated my original content with these new ideas. 

I wasn't aware that [the M10 FHD page](https://wiki.ubports.com/wiki/BQ-m10-FHD-workarounds?hl=m10) existed. Is it still relevant?

**Comment by NeoTheThird** [comment]
I think it's not. Confirm @mariogrip?

**Comment by olisax** [comment]
Concerning the *DAV synchronization I proposed a [commit](https://github.com/ubports/docs.ubports.com/commit/d4e2bbb77e9a4a0d59f9a5d0916eada74ac84155) :-)

**Comment by doniks** [comment]
How about we close THIS issue? I think the big move has been done.
In case there are any specific pieces that still need attention please make separate specific issues. Right now I can't see what is the actionable item(s) in here. I'm happy to help, but I don't know what

**Comment by UniversalSuperBox** [comment]
Yeah, you're right. I think this is done.
