### ISSUE TITLE
qt version used in clickable

### ISSUE THREAD

**Issue by kwoot** [ubports/docs.ubports.com#417]
So, following the documentation I do a clickable desktop and it says:

```
clickable desktop
Parameter "template" is deprecated in clickable.json. Use "builder" as drop-in replacement instead.
Unable to find image 'clickable/amd64-16.04-amd64-nvidia:16.04.4-qt5.9' locally

```
But didn't we switch with ota-16 to qt5.12?
So, should the default image to build with change?

Or is it possible to say what version to use?

Greets,
Jeroen Baten

**Comment by lduboeuf** [comment]
Clickable is just waiting for an update to make Qt5.12 the default, t should be there soon.
Meanwhile your can just do `CLICKABLE_QT_VERSION=5.12 clickable desktop` if you wish to build it with Qt5.12

**Comment by kwoot** [comment]
Good to know. Thanks!

**Comment by lduboeuf** [comment]
Can you close that issue then ?. 
Btw this repo is more for the doc itself, the main bug tracker is in https://github.com/ubports/ubuntu-touch
