### ISSUE TITLE
documentation structure proposal

### ISSUE THREAD

**Issue by lduboeuf** [ubports/docs.ubports.com#44]
hi,
found that `daily use` or `advance use` is not very accurate
my proposition for documentation structure: 

- ABOUT
  -   ...

- CONTRIBUTE
  - ...

- UBUNTU TOUCH INTERNALS
  - overview ( here we talk about OS architecture and Mobile specific things  )

- HOWTOS
  - Install Ubuntu Touch ( Here maybe find all things related to how install on supported device, howto port to new devices )
  - Switch release channels
  - Shell access via adb
  - Shell access via ssh
  - Screen Casting your UT device to your computer
  - Reverse tethering

    - ...
- APP DEVELOPPEMENT
  - Overview (intro confinement, link to ubuntu touch internals, click, languages, content hub, notifications, ... )
  - Build & Deploy
    - Install ( raw style )
    - Clickable
    - Ubuntu SDK IDE
  - Webapps 
    - ...
  - Native apps
    - ... 
  - Desktop X apps  (with libertine and non-official way)
  - External resources (tutorials, templates, blogs)
   -  ...

**Comment by lduboeuf** [comment]
maybe not the right place for fast collaborative document work. Etherpad or something somewhere ?

**Comment by NeoTheThird** [comment]
Not that different from the current arch, what exactly are you trying to solve?

**Comment by NeoTheThird** [comment]
So you're shuffling the order of the sections in the sidebar around and use more subheadings in the sidebar in userguide?

**Comment by NeoTheThird** [comment]
Maybe send a PR with your changes so we can see what exactly it is you want

**Comment by lduboeuf** [comment]
right, documentation is not an easy task but definitely needed :)
