### ISSUE TITLE
Meizu mx4's image finally disappeared

### ISSUE THREAD

**Issue by Fuseteam** [ubports/docs.ubports.com#502]
the link to the legacy image of the mx4 on https://docs.ubports.com/en/latest/userguide/install.html?highlight=legacy#install-on-legacy-android-devices, 404s i have found the file through the wayback machine https://web.archive.org/web/20211124001129/https://people.canonical.com/~alextu/tangxi/684.zip

we may want to look into how we'll handle this

**Comment by Flohack74** [comment]
@doniks yes send me the image by Telegram plz
