### ISSUE TITLE
Document the new things for porting to Focal

### ISSUE THREAD

**Issue by peat-psuwit** [ubports/docs.ubports.com#504]
In addition to #492, we need to document changes that come with Focal in the view of porters. Many changes are due to our migration to Systemd init system.

The following has to be documented. This list will be updated as more things are discovered.

- [ ] The changes in USB mode support.
  - usb-moded configuration (https://gitlab.com/ubports/core/packaging/usb-moded/-/wikis/home)
  - Support for forcing ADB or SSH mode depends on porters' preference (https://gitlab.com/ubports/core/packaging/usb-moded/-/merge_requests/4)
  - A secondary SSH daemon on port 8022 over USB. (https://gitlab.com/ubports/core/packaging/usb-moded/-/merge_requests/4)
- [ ] Changes in bluetooth-touch package for Systemd (https://gitlab.com/ubports/core/bluetooth-touch/)
  - Probably relevant to Android 7 devices, since Bluebinder obsolete that for Android 9+.
- [ ] General changes for Systemd units (one may find https://wiki.ubuntu.com/SystemdForUpstartUsers#Job_vs._unit_keywords useful)

**Comment by gber** [comment]
Can you elaborate a bit more, particularly how you'd prefer this to be structured and where to put it (integrate with existing pages, new sections)?

**Comment by peat-psuwit** [comment]
To be honest, I'm not sure yet... Currently what we definitely should have is a dedicated page which helps porters coming from Xenial to move their ports to Focal. We'll want to have something for new porters too. I'm just not sure if it should be a new section or a modification to the existing pages...

**Comment by luksus42** [comment]
@peat-psuwit Hey, I just added the usb-moded config for the Lenovo x605 and must say that it works like a charm. :-)
It enabled usb mtp mode and adb (with developer mode enabled) without issues so far, and it was way more easy, than it was on xenial. Thanks for this. :+1: 

In my opinion,  at least the usb-moded wiki entry could be taken as it is into the documentation under "Porting/Configuring, Testing, Fixing".
