### ISSUE TITLE
Deprecate Anbox informations, create Waydroid page

### ISSUE THREAD

**Issue by Flohack74** [ubports/docs.ubports.com#541]
After Waydroid became a good success on UT and Anbox development is stopped it is necessary to reflect this inour documentation.

**Comment by JamiKettunen** [comment]
Old Anbox page: https://github.com/ubports/docs.ubports.com/blob/master/userguide/dailyuse/anbox.rst / https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html

**Comment by JamiKettunen** [comment]
https://docs.ubports.com/en/latest/userguide/dailyuse/waydroid.html is now available after #561 so this shall be closed :)
