### ISSUE TITLE
s/ARCHITECTURE_TRIPLET/ARCH_TRIPLET/

### ISSUE THREAD

**Issue by jmlich** [ubports/docs.ubports.com#571]
It seems ARCHITECTURE_TRIPLET is obsolete syntax and it should be replaced with ARCH_TRIPLET

It should be replaced here
https://github.com/ubports/docs.ubports.com/blob/2958bffea503314846afe773baca4c5998f87fe1/appdev/guides/dependencies.rst?plain=1#L112-L113

**Comment by doniks** [comment]
Indeed. Would you be up to making a pull request to fix it?

**Comment by jmlich** [comment]
Pull request created

**Comment by Fuseteam** [comment]
@jmlich where is the pull request?

**Comment by jmlich** [comment]
I am sorry, the commit was created, but I forgot to create pull request..
