### ISSUE TITLE
Why the docs have "porting" insturcitions only for up to halium 9.0 if it says that halium 10.0 and 11.0 are supported as well?

### ISSUE THREAD

**Issue by rempas** [ubports/docs.ubports.com#573]
The title is pretty much self explanatory? I am confused and I don't understand. Is there something I am missing? Should the steps for halium 9.0 be followed for 10.0 and 11.0 as well so the later are not mentioned?

Can somebody makes things more clear in the docs please?

**Comment by lduboeuf** [comment]
hope you found the answer. And please share your findings , maybe by contributing to the documentation ?

**Comment by NotKit** [comment]
Solved by #558
