### ISSUE TITLE
Wrong sample code for Ubuntu.Components ViewItems under dragUpdated section

### ISSUE THREAD

**Issue by kugiigi** [ubports/docs.ubports.com#77]
## Description
In the first example, it uses the syntax `ListViewDrag` however it is incorrect. 
The correct syntax is `ListItemDrag`.

https://api-docs.ubports.com/sdk/apps/qml/Ubuntu.Components/ListItem.html#sdk-ubuntu-components-listitem-dragmode

**Comment by UniversalSuperBox** [comment]
@bhdouglass where do you think this issue lies?

**Comment by bhdouglass** [comment]
@UniversalSuperBox probably in the docs in the ubuntu components deb package.

**Comment by cibersheep** [comment]
This is fixed, isn't it?

**Comment by mymike00** [comment]
I think it is. @kugiigi can you please confirm it got fixed?

**Comment by kugiigi** [comment]
I honestly don't remember this anymore but I checked and see `ListItemDrag` so I guess this is indeed fixed 😄

**Comment by cibersheep** [comment]
Good... so, if it. Could you close the issue ^__^?

**Comment by kugiigi** [comment]
Fixed
