### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Anne017** [ubports/docs.ubports.com#95]
In docs.ubports.com/porting/building-ubports-boot.rst:

Now that you have ubports-boot built, you can move on to :doc:`installing-16-04`.

Should be something like:

Now that you have ubports-boot built, you can move on to :doc:`installing-16-04 <userguide/install>`.

**Comment by UniversalSuperBox** [comment]
That link seems to go to https://docs.ubports.com/en/latest/porting/installing-16-04.html, which is the correct location.
